# Generated by Django 4.2.1 on 2023-05-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_remove_movie_starring_movie_img_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='img',
            new_name='imgs',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='years',
        ),
    ]
