# Generated by Django 4.2.1 on 2023-05-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_rename_img_movie_imgs_rename_year_movie_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='years',
            field=models.TextField(),
        ),
    ]
