# Generated by Django 4.2.1 on 2023-05-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_movie_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='years',
        ),
    ]
