# Generated by Django 4.2.1 on 2023-05-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_remove_movie_imgs_remove_movie_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imgs',
            field=models.ImageField(default='imggg', upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='years',
            field=models.TextField(default=1990),
            preserve_default=False,
        ),
    ]
